channels:
- defaults
dependencies:
- alabaster=0.7.9=py35_0
- babel=2.3.4=py35_0
- dbus=1.10.10=0
- docutils=0.13.1=py35_0
- expat=2.1.0=0
- fontconfig=2.12.1=2
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- icu=54.1=0
- imagesize=0.7.1=py35_0
- jinja2=2.9.4=py35_0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=0.23=py35_2
- mkl=2017.0.1=0
- numpy=1.11.3=py35_0
- openssl=1.0.2k=0
- pcre=8.39=1
- pip=9.0.1=py35_1
- pygments=2.1.3=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.2=0
- pytz=2016.10=py35_0
- qt=5.6.2=3
- qtpy=1.2.1=py35_0
- readline=6.2=2
- requests=2.12.4=py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.5.1=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - pyqtgraph==0.10.0

